// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkvW-kDOEScJMCHKl_OHwxsAup1yFNFw',
    appId: '1:160863676221:web:435324d9788cca2b688754',
    messagingSenderId: '160863676221',
    projectId: 'as-shopsync',
    authDomain: 'as-shopsync.firebaseapp.com',
    storageBucket: 'as-shopsync.firebasestorage.app',
    measurementId: 'G-99BL9Z5BF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZk684FxerVghyIEcgakbux2C47aN0VUc',
    appId: '1:160863676221:android:f99b71c26d255a7a688754',
    messagingSenderId: '160863676221',
    projectId: 'as-shopsync',
    storageBucket: 'as-shopsync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHMLivJ_ils_XU8JzC1MfXSokb9lhikI',
    appId: '1:160863676221:ios:6ef27517b738f2ef688754',
    messagingSenderId: '160863676221',
    projectId: 'as-shopsync',
    storageBucket: 'as-shopsync.firebasestorage.app',
    androidClientId:
        '160863676221-ajc4adkuqq2holdp7bl9imbmar6137le.apps.googleusercontent.com',
    iosClientId:
        '160863676221-ul8ri7astve08bn4mn9uucul9v6cciv3.apps.googleusercontent.com',
    iosBundleId: 'com.aadishsamir.shopsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuHMLivJ_ils_XU8JzC1MfXSokb9lhikI',
    appId: '1:160863676221:ios:6ef27517b738f2ef688754',
    messagingSenderId: '160863676221',
    projectId: 'as-shopsync',
    storageBucket: 'as-shopsync.firebasestorage.app',
    iosClientId:
        '160863676221-ul8ri7astve08bn4mn9uucul9v6cciv3.apps.googleusercontent.com',
    iosBundleId: 'com.aadishsamir.shopsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkvW-kDOEScJMCHKl_OHwxsAup1yFNFw',
    appId: '1:160863676221:web:7001eaf6e9a008fa688754',
    messagingSenderId: '160863676221',
    projectId: 'as-shopsync',
    authDomain: 'as-shopsync.firebaseapp.com',
    storageBucket: 'as-shopsync.firebasestorage.app',
  );
}
