name: Deploy to Play Store Production

on:
  workflow_dispatch:

jobs:
  build:
    environment: google-play-deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      # Step 3: Decode Keystore (from GitHub Secret)
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release-key.jks
        working-directory: android

      # Step 4: Create key.properties (using GitHub secrets)
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "storeFile=release-key.jks" >> key.properties
        working-directory: android

      # Step 5: Create sentry.properties (using GitHub secrets)
      - name: Create sentry.properties
        run: |
          echo "${{ secrets.SENTRY_PROPERTIES }}" >> sentry.properties

      # Step 6: Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 7: Build AAB (Android App Bundle) for release
      - name: Build AAB
        run: flutter build appbundle --release --obfuscate --split-debug-info=build/symbols

      # Step 8: Upload the generated AAB to Google Play Console
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.aadishsamir.shopsync
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          status: completed
          userFraction: 0.3335

      # Step 9: Upload debug symbols to Sentry
      - name: Upload debug symbols to Sentry
        run: flutter pub run sentry_dart_plugin
